### ISSUE TITLE
Specific Vehicle Rearm Costs not Working....?

### ISSUE THREAD

**Issue by ReDBaroN1** [oiad/service_points#3]
Hey man!

When I have this:
```
_rearm_costs = [
	["Flares",2000],
	["HMMWV_M1151_M2_CZ_DES_EP1_DZE",25000], // M134 & M2 special costs for a single vehicle type
	["HMMWV_M998A2_SOV_DES_EP1_DZE",25000], // M134 & M2 special costs for a single vehicle type
	["LandRover_MG_TK_EP1_DZE",25000], // M2 special costs for a single vehicle type
	["LandRover_Special_CZ_EP1_DZE",25000], // AGS30 & PKM special costs for a single vehicle type
	["ArmoredSUV_PMC_DZE",25000], // M134 & M2 special costs for a single vehicle type
	["UAZ_MG_TK_EP1_DZE",25000], // DSHKM special costs for a single vehicle type
	["Offroad_DSHKM_Gue_DZE",25000], // DSHKM special costs for a single vehicle type
	["BTR40_MG_TK_INS_EP1",25000], // DSHKM special costs for a single vehicle type
	["BAF_Jackal2_L2A1_W",25000], // DSHKM special costs for a single vehicle type
	["AH6J_EP1_DZE",25000], // M134 Heli
	["UH1Y_DZE",25000], // M134 Heli
	["UH60M_EP1_DZE",25000], // M134 Heli
	["CH_47F_EP1_DZE",25000], // M134 Heli	
	["Air",2000], // 5 10oz Gold for other helicopters and planes
	["AllVehicles",2000] // 1 10oz Gold for all other vehicles
];
```
It seems to still give me the default cost (5k) when rearming in any of those vehicles. Do, I have to use ammo type? The examples show vehicles in there....

If I use ammo type, how do you work out the name for the ammo? Is it just copy pasting the first part of your ammo example `str_dn_` and adding `M134` or `M2` to the end?

Thanks

**Comment by ReDBaroN1** [comment]
Just tried this:
`_rearm_costs = [
	[localize "str_dn_M134",25000],
	[localize "str_dn_M2",25000],
	[localize "str_dn_DSHKM",25000]
];`
...and still picks up the default cost of 5k...

**Comment by ReDBaroN1** [comment]
Tried this too:
`_rearm_costs = [
	["2000Rnd_762x51_M134",25000],
	["100Rnd_127x99_M2",25000],
	["150Rnd_127x107_DSHKM",25000]
];`
Still goes to default cost...

**Comment by ReDBaroN1** [comment]
Got it! This works:
`_rearm_costs = [
	["M134",25000],
	["M2",25000],
	["DSHKM",25000]
];`
But, only this works....not sure if you want to update the instructions :)

**Comment by oiad** [comment]
Little bit late but the way the localize works is just by using some of the internal arma localizations (which are annoying to find)

It's not done by vehicle classname as per your first but rather the gun name
